config/routes.rb
Parking::Application.routes.draw do

  resources :events

  match 'lots/delta' => 'lots#delta', :as => :delta
  
  resources :lots

  root :to => 'lots#index'

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  attr_accessible :name, :cars, :total_spots, :type_type
  
  validates_presence_of :total_spots, :cars, :type_type, :name

  before_validation :normalize_lot_color
  validate :valid_lot_color?

  has_many :coordinates

  def normalize_lot_color
      if self.type_type and self.type_type.is_a? String
          self.type_type = self.type_type.downcase
      end
  end

  def valid_lot_color?
      if ['blue', 'red', 'yellow'].include? self.type_type
          true
      else
          errors.add(:type_type, "Lot color is not valid")
          false
      end
  end
  
end

app/controllers/admin/lots_controller.rb
class Admin::LotsController < ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lots }
    end
  end

  def delta
    @lot = Lot.find_by_name(params[:name])

    respond_to do |format|
      if @lot.update_attributes(:cars => (@lot.cars + Integer(params[:delta])))
        format.html { redirect_to [:admin,@lot], notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to admin_lots_path, notice: 'Lot was successfully created.' }
        format.json { render json: @lot, status: :created, location: @lot }
      else
        format.html { render action: "new" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to [:admin,@lot], notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to admin_lots_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lots }
    end
  end

  def delta
    @lot = Lot.find_by_name(params[:name])

    respond_to do |format|
      if @lot.update_attributes(:cars => (@lot.cars + Integer(params[:delta])))
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to lots_path, notice: 'Lot was successfully created.' }
        format.json { render json: @lot, status: :created, location: @lot }
      else
        format.html { render action: "new" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to lots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lots_helper.rb
module LotsHelper
    def get_coords(lot, size=:medium)
      # returns a comma separted list of coordinates for use in an html map.
      # i.e. x1,y1,x2,y2,...etc
      x_resize_ratio = get_ratio_for_dimension( size, Parking::Application.config.x )
      y_resize_ratio = get_ratio_for_dimension( size, Parking::Application.config.y )

      coordinates = lot.coordinates.collect do |coord|
        "#{(coord.x * x_resize_ratio).ceil},#{(coord.y * y_resize_ratio).ceil}"
      end

      coordinates.join(',')
    end

    def get_image_name( size=:medium )
      "parking_square_#{size.to_s}.png"
    end

    def get_size_for_dimension( size, dim )
      Parking::Application.config.parking_image_size[size][dim]
    end

    private

    def get_ratio_for_dimension( size, dim )
      Parking::Application.config.parking_image_size[size][dim] / Parking::Application.config.parking_image_size[:original][dim].to_f
    end

end

app/views/lots/_form.html.erb
<%= form_for(@lot) do |f| %>
  <% if @lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% @lot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lots/_form.html.haml
= form_for(@lot) do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Lot

    - if @lot.errors.any?
      #error_explanation
        %h2
          = pluralize(@lot.errors.count, "error")
          prohibited this lot from being saved:
        %ul
          - @lot.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :total_spots, "Total Spots"
      = f.number_field :total_spots
    .field
      = f.label :cars
      = f.number_field :cars
    .field
      = f.label :type_type, "Type"
      = f.select(:type_type, %w[ commuter general ], { :include_blank => false })
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', lots_path, :class => 'btn'

app/views/lots/index.html.erb
<div class="page-header">
<h1>Parking Lots</h1>
</div>

<table class="table table-striped">
<thead>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
<% @lots.each do |lot| %>
  <tr>
    <td><%= lot.name %></td>
    <td>
    <%= link_to 'Show', lot, :class => 'btn btn-mini' %>
    <%= link_to 'Edit', edit_lot_path(lot), :class => 'btn btn-mini' %>
    <%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<div class="form-actions">
    <%= link_to 'New Lot', new_lot_path, :class => 'btn' %>
</div>

app/views/lots/index.html.haml
= render "side_pane"
.mapview
  %map{name:"lot_spots"}
    - @lots.each do |lot|
      %area{shape:"poly",coords:get_coords(lot, :medium),href:lot_path(lot)}

  = image_tag get_image_name(:medium), usemap: "#lot_spots", ondragstart: "return false" #the ondragstart thing is to prevent draggin the image (better ux)

app/views/lots/show.html.haml
%fieldset
  %legend
    = @lot.name
    %small
      (
      = @lot.type_type
      )

%p
  %b Total Spots:
  = @lot.total_spots
%p
  %b Cars in Lot:
  = @lot.cars

.form-actions
  = link_to 'Edit', edit_lot_path(@lot), :class => 'btn'
  = link_to 'Cancel', lots_path, :class => 'btn'