config/routes.rb
Parking::Application.routes.draw do

  resources :events

  match 'lots/delta' => 'lots#delta', :as => :delta
  
  resources :lots

  root :to => 'lots#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Parking
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    /= favicon_link_tag "favicon.ico"
    = csrf_meta_tags
    %meta{id:"viewport",
          name:"viewport",
          content:"width=device-width; initial-scale=1; maximum-scale=1; user-scalable=0;"}

  %body
    .navbar
      .navbar-inner
        .container
          %ul.nav
            %li
              %span.brand= link_to "acmX - Parking", root_path
            %li= link_to 'Parking Lots', lots_path, :title => "Click to see all parking lots"
    #body
      .container
        .row
          .span2
            .sidebar-nav.sidebar-nav-fixed
              = content_for :side_pane
          .span10
            #flashcontainer
              - flash.each do |key, msg|
                - if key == :information
                  .alert.alert-info
                    %button.close{:'data-dismiss' => "alert"} ×
                    = msg
                - if key == :notice
                  .alert.alert-success
                    %button.close{:'data-dismiss' => "alert"} ×
                    = msg
                - if key == :warning
                  .alert
                    %button.close{:'data-dismiss' => "alert"} ×
                    = msg
                - if key == :error
                  .alert.alert-error
                    %button.close{:'data-dismiss' => "alert"} ×
                    = msg
            = yield